# Generated by Django 3.1.1 on 2020-09-14 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 22, 38, 9, 739664, tzinfo=utc)),
        ),
    ]
