# Generated by Django 3.1.2 on 2020-11-07 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20200914_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='detalhamento',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
