# Generated by Django 3.1.2 on 2021-06-16 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_auto_20201107_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 11, 34, 44, 311251, tzinfo=utc)),
        ),
    ]
