# Generated by Django 3.1.2 on 2021-06-16 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_auto_20210616_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='InicioAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 11, 43, 21, 260677, tzinfo=utc)),
        ),
    ]
