# Generated by Django 3.2.5 on 2021-07-27 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_auto_20210616_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='cor',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 7, 27, 19, 49, 9, 443102, tzinfo=utc)),
        ),
    ]
