# Generated by Django 3.2.5 on 2021-07-29 20:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atividades', '0008_auto_20210729_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 7, 29, 20, 28, 35, 27310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
