# Generated by Django 4.0 on 2022-01-30 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_auto_20210729_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='area',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='atividades.area'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 15, 0, 45, 845184, tzinfo=utc)),
        ),
    ]
