# Generated by Django 4.0 on 2022-01-30 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0013_area_usuario_alter_atividade_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=datetime.datetime(2022, 1, 30, 17, 33, 1, 854045, tzinfo=utc)),
        ),
    ]
